version: '3.8'

services:
  db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: pokemon
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'