name: pokemon-pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: db_url
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      
      # Debug environment variables
      - name: Debug Environment
        run: env
      
      # Confirm if the variable is set
      - name: Check ACCESS_KEY
        run: '[ -n "$ACCESS_KEY" ] && echo "ACCESS_KEY is set" || echo "ACCESS_KEY is not set"'

      # Print ACCESS_KEY securely
      - name: Echo Access Key
        run: echo "$ACCESS_KEY"
