name: pokemon-pipeline

on:
  push:
    branches:
      - main 

permissions:
  id-token: write
  contents: read 

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up Java plugin...
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Installing dependencies...
        run: mvn clean install -DDB_URL=${{ secrets.DB_URL }} -DDB_PASSWORD=${{ secrets.DB_PASSWORD }} -DSECRET=${{ secrets.SECRET }} -DDB_USER=${{ secrets.DB_USER }} -DskipTests
      - uses: actions/upload-artifact@v4 
        with: 
          path: .
          name: build-package
  build:
    needs: install
    runs-on: ubuntu-latest
    environment: db_url
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
          name: build-package
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
      - name: Setting up Java plugin...
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Building Java application
        run:  mvn clean package -DskipTests
#        run: mvn clean package -DDB_URL=${{ secrets.DB_URL }} -DDB_PASSWORD=${{ secrets.DB_PASSWORD }} -DSECRET=${{ secrets.SECRET }} -DDB_USER=${{ secrets.DB_USER }} -DskipTests

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Logging to ECR...
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c5b5b5a8
      - name: Build Docker image
        run: docker build -t fernandocesxr/pokemon-api .
      - name: Tagging image...
        run: docker tag fernandocesxr/pokemon-api:latest public.ecr.aws/c5b5b5a8/fernandocesxr/pokemon-api:latest
      - name: Pushing image...
        run: docker push public.ecr.aws/c5b5b5a8/fernandocesxr/pokemon-api:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: db_url
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
      - name: deploying into aws
        run: aws ecs update-service --cluster "fernandocesxr-pokemon-api-container" --service "pokemon-api-service" --task-definition "arn:aws:ecs:us-east-1:025066237585:task/fernandocesxr-pokemon-api-container/e76c5c3a796048329c4d2e2e7f19026e"
  finally:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Congratulations you are all set!!!🎉🎉🎉"

