name: pokemon-pipeline
on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up java plugin...
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Installing dependencies...
        run: mvn clean install
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up java plugin...
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Building java application
        run: mvn clean package -Ddb_url={{ secrets.db_url }} -Ddb_password={{ secrets.db_password }} -Dsecret={{ secrets.secret }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4